systemd/journal.py
Python 2.7/3.2 introduce a function [`timedelta.total_seconds()`](https://docs.python.org/3/library/datetime.html#timedelta-objects). The function `timedelta.totalseconds()` used previously is undefined.
=> Fixes Reader.seek_monotonic(datetime.timedelta)

README.md
readme: Minor fixes:
- remove duplicate 'is thrown'
- Use "raised" instead of "thrown"
=> readme: Remove duplicate 'is thrown'

setup.py
PKG_CONFIG is the standard environment variable used by e.g. autotools to force a custom pkg-config. We use it for building packages to make sure that only the .pc files from the right directories are picked up which is especially important during cross-compiling.
=> setup.py: respect ${PKG_CONFIG} if set

README.md
I was trying to build `python-systemd` from source but ran into the same issue here: https://github.com/systemd/python-systemd/issues/17
I Figure the docs should be updated to reflect this dependency.
=> Updating docs for missing dependency

systemd/journal.py
This approach allows to use LoggerAdapter+extra or .info(.., extra={})
to transparently add extra fields to journal.
=> Include all fields from record + additional fields with exception info if any

systemd/journal.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
=> Python 3.6 invalid escape sequence deprecation fixes

systemd/test/test_daemon.py
This bind() call may fail if TMPDIR is too long.
Bug: https://bugs.gentoo.org/610368
=> test_daemon: xfail test_notify_with_socket if bind() fails

systemd/journal.py, systemd/test/test_journal.py
py3 doesn't have `dict.iteritems()` anymore so it fails under py3 env. So replace `dict.iteritems()` with `dict.items()`. `six.iteritems()` can be used but it requires `six` as a dependency library.
Previous test cases doesn't reveals the failure under py3 env so introduce a MockSender and inject sender function to increase testability.
=> replace dict.iteritems() with dict.items() to support py3

setup.py, systemd/_daemon.c, systemd/_reader.c, systemd/daemon.py, systemd/journal.py, systemd/test/test_daemon.py, systemd/test/test_journal.py, systemd/util.c, systemd/util.h
Later on a proper wrapper in daemon.py should be added.
This should wait until the support in systemd is merged.
=> daemon: add basic support for sd_is_socket_sockaddr

systemd/journal.py
This was causing an exception to be thrown when used with Django as a logging handler.
I found that these changes seem to fix it.
=> Prevent non-str values from being concatenated with +

systemd/journal.py, systemd/test/test_journal.py
This change is to update the styling within `journal.py` to be more consistent with PEP8.
=> Fix styling to match PEP8 in most places

systemd/journal.py, systemd/test/test_journal.py
Replacement for #38, rebased and with some fixes on top and tests.
=> Remove mid from journal.py

README.md
I guess many people would like to search the handler class for the logging framework. However, the README doesn't provide a example for the `journal.JournalHandler`. Then they may turn to use other python wrappers like [mosquito/python-systemd](https://github.com/mosquito/python-systemd).
So I think the `journal.JournalHandler` example should be added in README.
=> add JournalHandler usage in README

systemd/_daemon.c
reproducible with 
```python
import sys
import systemd.daemon
fd = 1
fds = [fd]
ref_cnt = sys.getrefcount(fd)
systemd.daemon.notify('', True, 0, fds)
assert sys.getrefcount(fd) <= ref_cnt, 'leak'
```
=> Fix notify fs leak

systemd/journal.py
`strftime("%s")` is not in the official python documentation but in my system (ubuntu 18.04 python 3.6.9) it is not aware of the object timezone and will return the wrong value if the timezone is specified and is not the system local one.
There are multiple ways to ensure a python `datetime.datetime` is in local timezone, the easiest (with python 3.3+) is to call `.astimezone()` If one wants to support earlier versions of python an extra dependency might be needed like `dateutil.tz.tzlocal()`.
=> Fix seek_realtime to work with timezone aware date

systemd/_reader.c, systemd/journal.py
Add log namespace support which is added since systemd v245
If reader `namespace` parameter is specified, the log will be read from specific `systemd` namespace
=> journal: add namespace support

README.md
"libsytemd" should obviously be "libsystemd"
=> fix a mistype in README.md

README.md
There are a few issues requesting documentation for common use cases (eg. #83) so I've added a few lines to the README to demonstrate common ways to read from the journal (inspired by examples on the [arch linux wiki page on the systemd journal](https://wiki.archlinux.org/index.php/Systemd/Journal)).
Let me know if you think it would fit better somewhere else or could use some other examples that I haven't thought of.  I know some of this is in the [official docs](https://www.freedesktop.org/software/systemd/python-systemd/journal.html) but IMO there's room for both.
=> Journal examples

setup.py
In Python 3.10, distutils is deprecated and slated for removal in Python
3.12. It also prevents 'setup.py bdist_wheel' from building a wheel.
Signed-off-by: Tim Orling <tim.orling@konsulko.com>
=> setup.py: switch from distutils to setuptools

systemd/_reader.c
From the docs:
> `|` Indicates that the remaining arguments in the Python argument list are optional. The C variables corresponding to optional arguments **should be initialized to their default value** — when an optional argument is not specified, [PyArg_ParseTuple()](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple) does not touch the contents of the corresponding C variable(s).
=> Fix use of potentially uninitialized value

systemd/journal.py, systemd/test/test_journal.py
Currently, converters for timestamp fields (__REALTIME_TIMESTAMP, _SOURCE_REALTIME_TIMESTAMP, COREDUMPTIMESTAMP) produce datetimes object without timezone, losing information.
This PR fixes that.
Without this commit :
```
>>> from systemd import journal
>>> j = journal.Reader(flags = journal.CURRENT_USER)
>>> j.seek_tail()
>>> j.get_previous().isoformat()
>>> j.get_previous()['__REALTIME_TIMESTAMP'].isoformat()
'2022-01-08T20:44:23.000494'
```
And with this commit :
```
>>> j.get_previous()['__REALTIME_TIMESTAMP'].isoformat()
'2022-01-08T20:44:23.000494+01:00'
```
Reference: [datetime.fromtimestamp](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) : 
> If optional argument tz is None or not specified, the timestamp is converted to the platform’s local date …
=> Adding timezone information to datetimes from systemd-journal

systemd/_reader.c, systemd/journal.py
Output from `journalctl` is prepended with a string like:
```
-- Journal begins at Mon 2020-11-23 02:18:37 UTC, ends at Sat 2021-01-02 22:20:10 UTC. --
````
which is generated using the `sd_journal_get_cutoff_realtime_usec` call. This PR adds the capability to access these values from inside the python wrapper by exposing `get_start()` and `get_end()` methods on the journal object, returning a `datetime`. Addresses #84. 
It's been a while since I've used the Python C API, happy to address feedback if anyone has time.
=> Support realtime cutoff access

.github/workflows/install.yml, systemd/test/test_id128.py, systemd/test/test_journal.py
=> tests: check for errnos that sd_id128_get_machine actually returns

systemd/_daemon.c, systemd/_journal.c, systemd/_reader.c, systemd/id128.c, systemd/journal.py, systemd/login.c, systemd/pyutil.c, systemd/pyutil.h, systemd/test/test_daemon.py
I had this lying around on some private branch, seeing the movement here, I remembered that I might push it. Python 2 has been EOL for 2 years now and everything older 3.7 is EOL as well, so assuming Python 3.3+ seems sensible (also nothing older thatn 3.7 is being tested).
=> Remove python 2 support and assume we have python 3.3+

README.md
Missed an oopsie in #123, the url pointed to PyPI home page and not the project url. Sorry
=> Fixed PyPI url in last commit

README.md
Python 2 support was fully dropped in 802c8dcaa3096719be0a1c12 so it can be a bit confusing to advertise Python 2 build dependencies in the README.
=> README: stop mentioning Python 2 build dependencies

systemd/test/test_daemon.py
One usage of `connection_error` got missed when dropping Python 2 support.
=> Fix test failure

docs/conf.py
Newer sphinx doesn't like the old syntax:
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
ERROR: Invalid value `None` in intersphinx_mapping['http://docs.python.org/']. Expected a two-element tuple or list.
=> docs: update intersphinx_mapping

src/systemd/__init__.py, src/systemd/_daemon.c, src/systemd/_journal.c, src/systemd/_reader.c, src/systemd/id128.c, src/systemd/journal.py, src/systemd/login.c, src/systemd/macro.h, src/systemd/pyutil.c, src/systemd/pyutil.h, src/systemd/strv.c, src/systemd/strv.h, src/systemd/util.c, src/systemd/util.h
@poettering, @davidstrauss, @intgr, @kwirk please give your acks.
This mirrors the change that was done in systemd and in other projects.
The copyright is preserved even without an explicit copyright line, and those
lines get our of sync with the actual history of edits in a file, so let's drop them.
The copyright and license is still maintained.
=> Drop copyright tags
